[package]
name = 'helloextendr'
version = '0.3.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'helloextendr'

[dependencies]
extendr-api = {git = "https://github.com/sorhawell/extendr/", branch = "try_fix_leak"}
